
project_id = "ikuviazxpqpbomfaucom"
[api]
enabled = true
[auth]
enabled = true
[functions]
enabled = true
[functions.validate-template]
verify_jwt = false
[functions.crossmint-nft]
verify_jwt = false
