// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ikuviazxpqpbomfaucom.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlrdXZpYXp4cHFwYm9tZmF1Y29tIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2MTAwNzcsImV4cCI6MjA2MDE4NjA3N30.Uhe9ZPxc-UeCmw-Ao3eIjbo00Xd5_9KltR6zCjf6DUM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);